dataset_path: '/home/wei/Workspace/data/threedmatch_test'
weights: '/home/wei/Downloads/fcgf-pretrained.pth'
scenes: [7-scenes-redkitchen, sun3d-home_at-home_at_scan1_2013_jan_1, sun3d-home_md-home_md_scan9_2012_sep_30, sun3d-hotel_uc-scan3, sun3d-hotel_umd-maryland_hotel1, sun3d-hotel_umd-maryland_hotel3, sun3d-mit_76_studyroom-76-1studyroom2, sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika]
